### PR TITLE
Add support for mac target

### PR DESCRIPTION
**Pull request by marcoconti83**
Add macOS target and macOS unit tests

### CODE REVIEW

**Comment by vytis** [comment]
There is a trick on how to have single target for iOS and Mac, depending on your use case this might be a nicer solution - https://stackoverflow.com/questions/26811170/how-to-create-a-single-shared-framework-between-ios-and-os-x

**Comment by marcoconti83** [comment]
Good point, I will check it out

**Comment by marcoconti83** [comment]
The "single target" solution looks great, e.g. it avoids having to add files to both targets. However it doesn't allow to have separate `.xcconfig` files (or even target settings) for iOS and macOS, which might be a problem for some settings. One example is with framework include folders (`Carthage/build/ios` vs. `Carthage/build/mac`). There might be more cases in more complex frameworks higher up the chain. For now, I would keep two target.

**Comment by vytis** [comment]
Fair point. Also I remember several open source projects using this approach, can try to find which ones to see how they handle platform-specific configuration.

**Comment by vytis** [comment]
You can't have separate `.xcconfig` files for SDK, but it seems you can assign different build properties depending on SDK value as shown in here: https://pewpewthespells.com/blog/xcconfig_guide.html#ConditionalVariableAssignment.

The open-source repo I mentioned is https://github.com/Moya/Moya, but they don't have any special configuration and no `.xcconfig` files. They do it the project settings like this:
screen shot 2017-06-12 at 15 28 43

**Comment by marcoconti83** [comment]
Thanks for digging. I will check.

**Comment by marcoconti83** [comment]
Closed in favor of https://github.com/wireapp/wire-ios-system/pull/8, thanks to @vytis ' suggestions

**Pull request closed without merging**
