### PR TITLE
Xcode 10.0

### PR DESCRIPTION
**Pull request by alexaubry**
## What's new in this PR?

We update the framework to compile with Xcode 10.0.

- Bump target version to iOS 10.0
- Migrate to Swift 4.2
- Remove deprecated ASL Logging, as `os_log` is available in iOS 10

### Note

Do not merge until Jenkins uses Xcode 10 as well.

### CODE REVIEW

**Comment by mikeger** [comment]
@alexaubry Fastlane borked somehow:


> [02:52:51]: fastlane finished with errors
> 
> [!] No test result files found in directory '.', make sure the file name ends with 'TestSummaries.plist'

**Comment by vytis** [comment]
We need to update Fastlane, it doesn't know where to look for test results with new Xcode.

**Comment by vytis** [comment]
@mikeger update Fastlane and re-run tests - all seem to be working fine

**Comment by vytis** [comment]
@zenkins release major

**Pull request merged**
